# DataSource Config
spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/blog_first
    username: root
    password: 123456

server:
  port: 8080
  #  添加后端API接口路径
  servlet:
    context-path: /api

# application.yml
mybatis-plus:
  global-config:
    db-config:
      id-type: auto  # 全局自增主键策略
      logic-delete-field: isDelete # 全局逻辑删除字段名(isDelete为实体类属性名称)
      logic-delete-value: 1 # 逻辑已删除值。可选，默认值为 1
      logic-not-delete-value: 0 # 逻辑未删除值。可选，默认值为 0

